services:
  - type: web
    name: askpdf-api
    runtime: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    plan: free
    envVars:
      - key: NODE_VERSION
        value: 22
      - key: NODE_ENV
        value: production
      - key: REDIS_URL
        sync: false
      - key: QDRANT_URL
        sync: false
      - key: QDRANT_API_KEY
        sync: false
      - key: HUGGINGFACE_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: CORS_ORIGIN
        sync: false

  - type: worker
    name: askpdf-worker
    runtime: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm run worker
    plan: free
    envVars:
      - key: NODE_VERSION
        value: 22
      - key: NODE_ENV
        value: production
      - key: REDIS_URL
        sync: false
      - key: QDRANT_URL
        sync: false
      - key: QDRANT_API_KEY
        sync: false
      - key: HUGGINGFACE_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false